# Generated by Django 4.2.11 on 2026-06-13 17:23

from django.db import migrations, models


def normalize_tournament_sizes(apps, schema_editor):
    Tournament = apps.get_model('tournaments', 'Tournament')
    Tournament.objects.filter(max_players__lt=16).update(max_players=16)
    Tournament.objects.filter(max_players__gt=32).update(max_players=32)


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentteam_tournamentmatch'),
    ]

    operations = [
        migrations.RunPython(normalize_tournament_sizes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tournament',
            name='max_players',
            field=models.IntegerField(choices=[(16, '16'), (32, '32')], default=16),
        ),
    ]
