# Generated by Django 4.2.11 on 2026-06-15 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seasons', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('SOLO', '1v1 — individuel'), ('TEAM', '2v2 — équipes ad-hoc'), ('FUN', '2v1 — match libre uniquement')], default='SOLO', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('VALIDATED', 'Validé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=10)),
                ('is_ranked', models.BooleanField(default=True)),
                ('score_player1', models.IntegerField(default=0)),
                ('score_player2', models.IntegerField(default=0)),
                ('elo_solo_player1_before', models.IntegerField(db_column='elo_solo_p1_before', default=1000)),
                ('elo_solo_player1_after', models.IntegerField(db_column='elo_solo_p1_after', default=1000)),
                ('elo_solo_player2_before', models.IntegerField(db_column='elo_solo_p2_before', default=1000)),
                ('elo_solo_player2_after', models.IntegerField(db_column='elo_solo_p2_after', default=1000)),
                ('elo_team_p1_before', models.IntegerField(default=1000)),
                ('elo_team_p1_after', models.IntegerField(default=1000)),
                ('elo_team_p1tm_before', models.IntegerField(default=1000)),
                ('elo_team_p1tm_after', models.IntegerField(default=1000)),
                ('elo_team_p2_before', models.IntegerField(default=1000)),
                ('elo_team_p2_after', models.IntegerField(default=1000)),
                ('elo_team_p2tm_before', models.IntegerField(default=1000)),
                ('elo_team_p2tm_after', models.IntegerField(default=1000)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player1_teammate', models.ForeignKey(blank=True, help_text='Coéquipier de player1. Renseigné pour TEAM et TWO_V_ONE.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player1_teammate', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL)),
                ('player2_teammate', models.ForeignKey(blank=True, help_text='Coéquipier de player2. Renseigné uniquement pour TEAM.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player2_teammate', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='seasons.season')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='RankingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('SOLO', '1v1'), ('TEAM', '2v2')], max_length=10)),
                ('scope', models.CharField(choices=[('season', 'Saisonnier'), ('global', 'Global')], max_length=10)),
                ('score_before', models.IntegerField()),
                ('score_after', models.IntegerField()),
                ('score_delta', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_history', to='matches.match')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_history', to='seasons.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ranking_history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('SOLO', '1v1'), ('TEAM', '2v2')], max_length=10)),
                ('scope', models.CharField(choices=[('season', 'Saisonnier'), ('global', 'Global')], max_length=10)),
                ('score', models.IntegerField(default=1000)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('season', models.ForeignKey(blank=True, help_text='NULL pour le scope global.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='seasons.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rankings',
                'ordering': ['-score'],
                'unique_together': {('user', 'season', 'mode', 'scope')},
            },
        ),
    ]
