server {
    listen 443 ssl;
    server_name localhost;

    # Certificats SSL
    ssl_certificate     /etc/ssl/certs/transcendence.crt;
    ssl_certificate_key /etc/ssl/private/transcendence.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    # WebSockets (chat, notifs, temps réel)
    location /ws/ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # API REST → Django
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Frontend React
    location / {
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}