# Generated by Django 4.2.11 on 2026-06-02 23:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('elo_solo', models.IntegerField(default=1000, help_text='ELO individuel 1v1. Mis à jour à chaque match SOLO classé validé.')),
                ('elo_team', models.IntegerField(default=1000, help_text='ELO personnel en 2v2. Indépendant du partenaire.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=8, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(default='user', max_length=15)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('totp_secret', models.TextField(blank=True, null=True)),
                ('oauth_42_id', models.TextField(blank=True, null=True, unique=True)),
                ('gdpr_deleted', models.BooleanField(default=False)),
                ('wallet_tokens', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
